// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gouzenuxqwqsrqdygocg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdXplbnV4cXdxc3JxZHlnb2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODUyNDYsImV4cCI6MjA2NDU2MTI0Nn0.-BiUVVTHUNK8eu13NKKb_HAhwDyHsieo9WGs5TtYTPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});